tools:
  - class_name: verl.tools.mcp_checklist_tool.MCPChecklistTool
    config:
      rate_limit: 120
      type: mcp
      return_raw: true
      max_concurrency: 100
      dataset_path: ${oc.env:CHECKLIST_DATASET_PATH,/mnt/shared-storage-user/zhouyijin/workspace/MyProj/UQ/formal_version_open/data/rl_data/rl_data_selected_checklist_annotated_for_verl_uni.json}
      sglang_url:
        - ${oc.env:JUDGE_API_URL,http://127.0.0.1:10001/v1/chat/completions}
      sglang_model: ${oc.env:LLM_AS_A_JUDGE_NAME,Qwen/Qwen3-4B-Instruct-2507}
      temperature: 0.6
      top_p: 0.8
      max_new_tokens: 8000
      max_tokens: 8000
      retry_attempts: 1
      semaphore_size: 500
      timeout: 1200
    mcp:
      mcp_servers_config_path: ${oc.env:CHECKLIST_MCP_SERVER_CONFIG,/mnt/shared-storage-user/zhouyijin/workspace/MyProj/UQ/formal_version_open/data/cm2_config/checklist_mcp_server.json}
      # optional
      tool_selected_list: []
